### ISSUE TITLE
Mulesoft CloudHub

### ISSUE THREAD

**Issue by bmik7216** [speedwing/log4j-cloudwatch-appender#19]
Apologies if this is a dumb question, but trying to setup our Mulesoft Logs to go to AWS CloudWatch and just wanted to know if this package could be used for Mulesoft CloudHub or if there was a tweak that could be made to make it work.

**Comment by nemo83** [comment]
not sure what Mulesoft is, but if it uses `log4j` as logging mechanism then yeah, you can configure it and have your logs sent to cloudwatch.

**Comment by bmik7216** [comment]
@nemo83 appreciate the quick response! Mulesoft is an integration platform. From reading this documentation: https://docs.mulesoft.com/mule-runtime/4.2/logging-in-mule 

I think I have to tweak this code to have an extra class that supports plugins like so: https://github.com/avioconsulting/log4j2-sqs-appender/blob/master/src/main/java/com/avioconsulting/log4j/sqs/SqsAppender.java

If this looks correct, would you be open to supporting a different branch for Mulesoft if I can get it working? That way this repo could support AnyPoint platform as well?

**Comment by nemo83** [comment]
I think this could be actually simpler. in Mule all that you need to do is to confiure a new appender with the CW appender of this project. 

If you come up with an improvement to this library, feel free to issue a PR and I'll happily review it

**Comment by naisla** [comment]
https://github.com/naisla/log4j2-cloudwatch-appender
