### ISSUE TITLE
Region is stuck as us-east-1

### ISSUE THREAD

**Issue by glynd** [speedwing/log4j-cloudwatch-appender#6]
Needs an ability to set the Region

**Comment by nemo83** [comment]
Not sure I fully understand. Can you give me an example of how you'd need a Region?

**Comment by glynd** [comment]
The AWS Logging client by default sends everything to us-east-1

If you have an application running in eu-west-1 (for example) you want to send logs to cloudwatch in eu-west-1 (not us-east-1)

See: https://github.com/aws/aws-sdk-java/issues/1221

Probable semi-fix (not tested yet)

AWSLogsClient --> AWSLogs      (private AWSLogs awsLogsClient;)

this.awsLogsClient = AWSLogsClientBuilder.standard().withRegion(Regions.EU_WEST_1).build();

**Comment by glynd** [comment]
Obviously region should be any optional parameter to the library

**Comment by nemo83** [comment]
I see now. It could be default to `us-east-1` and add a property via either properties file or programmatically in code.

I could use some help if you have time.

**Comment by glynd** [comment]
Tested on laptop, and on an instance 
Allows for the getRegion() to be overridden if someone wants something different. 
#7
